document.writeln("<footer>");
document.writeln("			<div class=\'mod_help\'>");
document.writeln("				<dl>");
document.writeln("					<dt>子站</dt>");
document.writeln("					<dd><a href=\'#\'>待添加</a></dd>");
document.writeln("					<dd><a href=\'#\'>待添加</a></dd>");
document.writeln("					<dd><a href=\'#\'>待添加</a></dd>");
document.writeln("				</dl>");
document.writeln("				<dl>");
document.writeln("				    <dt>友情链接</dt>");
document.writeln("				    <dd><a href=\'http://ser.chk.asia/link.php?d=https://bigtao.xyz\' title=\'每个人都是星辰\'>Bigtao小破站</a></dd>");
document.writeln("				    <dd><a href=\'http://ser.chk.asia/link.php?d=https://blog.maxwenyan23.top\'>Max温焰的blog</a></dd>");
document.writeln("					<dd><font size=\'5px\'><a href=\'/friend\'><img src=\'/image/ws.png\'/>申请友链</a></font></dd>");
document.writeln("				</dl>");
document.writeln("				<dl>");
document.writeln("					<dt>付费服务</dt>");
document.writeln("					<dd><a href=\'#\'>没有这玩意</a></dd>");
document.writeln("				</dl>");
document.writeln("			</div>");
document.writeln("			<div class=\'mod_copyright\'>");
document.writeln("				<div class=\'links\'>");
document.writeln("					<a href=\'http://ser.chk.asia/link.php?d=https://space.bilibili.com/531522938\'>站长B站</a>|");
document.writeln("					<a href=\'http://ser.chk.asia/link.php?d=mailto:2269718601@qq.com\'>联系我们</a>");
document.writeln("				</div>");
document.writeln("				<div class=\'copyright\'>");
document.writeln("					Copyright ©<span id=\'Date\'><script>getDate()</script></span> Sgss All Rights Reserved.");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("		</footer>");
