document.writeln("<div id=\'header\'>");
document.writeln("			<div class=\'logo\'>");
document.writeln("				<p style=\'font-size: 20px;\'>&#128213;&nbsp;Sgss小破站</p>");
document.writeln("			</div>");
document.writeln("			<ul>");
document.writeln("				<li class=\'nav\'><a href=\'/index_h5.html\'>主页</a></li>");
document.writeln("				<li><center><a class=\'nav\'>友情链接</a></center>");
document.writeln("					<ul>");
document.writeln("						<li><a href=\'http://ser.chk.asia/link.php?d=https://bigtao.xyz\'>Bigtao小破站</a></li>");
document.writeln("						<li><a href=\'http://ser.chk.asia/link.php?d=https://blog.maxwenyan23.top\'>Max的blog</a></li>");
document.writeln("					</ul>");
document.writeln("				</li>");
document.writeln("			</ul>");
document.writeln("		</div>");